### ISSUE TITLE
[BUG] Improve REDCapTidieR Execution Times and Benchmarking

### ISSUE THREAD

**Issue by rsh52** [CHOP-CGTDataOps/REDCapTidieR#48]
# Expected Behavior
`REDCapTidieR` should run relatively quickly (<10s) on most manageable databases. 

# Current Behavior
Currently `REDCapTidieR` can take long stretches of time that are not related to API calls. Using `profvis` it was found that the main culprit here is the `check_repeat_and_nonrepeat` function that gets looped through inside of the `clean_*` functions. This is a nested `for` loop that looks across rows and columns of a database to check whether a project is repeating or nonrepeating.

The complicating factor here is the allowed REDCap behavior to design an instrument that can be _both_ repeating **and** nonrepeating. This is a behavior we do not want to support, but wish to loudly fail on. If we can fix the below chunk for this check, it should greatly improve execution time:

https://github.com/CHOP-CGTDataOps/REDCapTidieR/blob/1c70017dff24b1600bfe18d79695af3ff148ae5e/R/checks.R#L67-L89

There may be some other areas that can marginally improve execution time, but this seems to be the biggest driving factor.

**Screenshots**
`profvis` outputs shown below:
![image](https://user-images.githubusercontent.com/38384694/196259221-37b35c15-0cb9-4ea9-8d16-1f260b2b2ea8.png)
![image](https://user-images.githubusercontent.com/38384694/196259278-770fe2d6-c69c-446d-bb6d-bd7398a6b37a.png)

### Checklist
Before submitting this issue, please check and verify below that the submission meets the below criteria:

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by ezraporter** [comment]
Some updates after diving deeper in the `profvis` output.

1. I think we were being misled by `profvis` a bit for reasons I'm not sure of. This is the current output from `profvis` in table form:
![profvis-tabular](https://user-images.githubusercontent.com/60618324/196793679-19caeb29-5e1c-43ed-9db2-e8bf250d6a32.png)

For some reason it's only attaching a small subset of the operations that are happening to `read_redcap_tidy`. The other portions are **definitely** things `read_redcap_tidy` is doing but `profvis` makes it hard to figure out what's happening where.

2. I made a new branch [here](https://github.com/CHOP-CGTDataOps/REDCapTidieR/tree/profiling) to dig into what's happening. I inserted some early returns into `read_redcap_tidy()` and then benchmarked the function in steps, running everything up to the return each time.

```r
devtools::load_all()
library(microbenchmark)

redcap_uri <- Sys.getenv("REDCAP_URI")
redcap_token <- Sys.getenv("PRODIGY_REDCAP_API")

# Run everything up to early return
read_redcap_tidy_early_return <- function(return_after) {
  read_redcap_tidy(redcap_uri, redcap_token, return_after = return_after)
}

microbenchmark(
  read_redcap_tidy_early_return(return_after = "redcap_read_oneshot call"),
  read_redcap_tidy_early_return(return_after = "checkbox/radio pre-process"),
  read_redcap_tidy_early_return(return_after = "everything"),
  times = 10
)

#> Unit: seconds
#>                              min       lq       mean      median        uq     max      neval
#> redcap_read_oneshot call     2.489722  2.623698  3.292804  2.954788  4.117324  4.584776    10
#> checkbox/radio pre-process  5.802323  6.114546  6.825518  6.665688  7.242212  8.974478    10
#> everything                   13.573109 13.696987 15.166749 14.701601 15.774709 19.008688    10

```

You can see where I inserted the early returns [here](https://github.com/CHOP-CGTDataOps/REDCapTidieR/commit/0d7921c8120adfb862c3e932e2c9fc1b258cc838)

(14.7 - 6.6) / 14.7 = 55% of our execution time is in that last chunk which basically just includes `clean_redcap_long` so I think the next step is finding a way to profile that logic individually.

**Comment by ezraporter** [comment]
Ignore everything I said. The **key** to `profvis` was setting `simplify = FALSE`:

```r
profvis::profvis(read_redcap_tidy(redcap_uri, redcap_token), simplify = FALSE)
```

That gives us useable output:
Table:
![profvis-tabular](https://user-images.githubusercontent.com/60618324/196971244-63093cc9-5be5-49b3-bf87-8cc75053a3cc.png)

Visual:
![profvis-graph](https://user-images.githubusercontent.com/60618324/196971254-08433a80-8b5a-4444-9c32-57e19eea7f1f.png)

**Comment by skadauke** [comment]
Wondering if using {dtplyr} for any of this might help?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ezraporter ***@***.***>
Sent: Thursday, October 20, 2022 11:14:47 AM
To: CHOP-CGTDataOps/REDCapTidieR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External]Re: [CHOP-CGTDataOps/REDCapTidieR] [BUG] Improve REDCapTidieR Execution Times and Benchmarking (Issue #48)


Looks like there are two big bottlenecks:

  1.  This filter operation in distill_*_table_long
[profvis1]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F60618324%2F196983423-cc211a7e-181a-46d3-892b-f39a2b423002.png&data=05%7C01%7Ckadaukes%40chop.edu%7C221db354985c431c343108dab2add587%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638018756923032355%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pgYJtoKkXRiveeOkD36mHA05%2F47QRETmAH7Ht29fDvM%3D&reserved=0>

We're currently looping over forms and longitudinal events. I think we should be able to do a single filter per form. If we need to do this repeated operation we might also save time by indexing into the data rather than using filter.

  1.  This piece of our conversion of raw checkbox values to labels
[profvis2]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F60618324%2F196984916-3ab2ea5f-8de2-4290-8278-299041be47d4.png&data=05%7C01%7Ckadaukes%40chop.edu%7C221db354985c431c343108dab2add587%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638018756923188591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GlPhAkhQ7LqhAdwBGze1CMnyfejG1B5pjMmaILxmXwA%3D&reserved=0>

If the mutate really is the problem we may be able to get away with renameing rather than mutateing

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCHOP-CGTDataOps%2FREDCapTidieR%2Fissues%2F48%23issuecomment-1285717234&data=05%7C01%7Ckadaukes%40chop.edu%7C221db354985c431c343108dab2add587%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638018756923188591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3xKKzF5CDHGpTpntUC5oi7%2FFEuVYznKPsXMYjlgQsmk%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTGHWQB7VMXET47VCRYUPLWEFOWPANCNFSM6AAAAAARHLKL4U&data=05%7C01%7Ckadaukes%40chop.edu%7C221db354985c431c343108dab2add587%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638018756923188591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hZM2AXKzPq5C7MSZU3vNFllVzWZqKTaw4DMaqq8XvYg%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by skadauke** [comment]
It might also be interesting to compare to `tidyREDCap::import_instruments()` which does something very similar to `read_redcap_tidy() |> bind_tables()`.

https://github.com/RaymondBalise/tidyREDCap/blob/master/R/import_instruments.R

**Comment by ezraporter** [comment]
See #56 for additional details but we can save about 4 seconds with a pretty simple optimization in `distill_*_table_long()`

**Comment by skadauke** [comment]
So where are we at now? Is it worth trying to wrestle one more bottleneck? I think 10 sec for the Prodigy DB are probably good enough but if there is one more significant and easily fixable bottleneck I would go for it

**Comment by ezraporter** [comment]
I think it may be worth it given the relative amount of time that step is now taking. It **feels** like it should be small compared to the rest of the processing we're doing. It also may not be too much work. #56 was really less than a day of work.
