### ISSUE TITLE
[FEATURE] Create utility function to apply {labelled} labels to supertibble

### ISSUE THREAD

**Issue by ezraporter** [CHOP-CGTDataOps/REDCapTidieR#64]
# Feature Request Description
A new exported function (`make_labelled()`) that uses the [`labelled`](http://larmarange.github.io/labelled/) package to apply labels to fields in the supertibble and fields within the supertibble's list columns.

# Proposed Solution
A use would run:
```r
suppertibble <- make_labelled(suppertibble)
```
which would:

1. Apply labels to the variables in the supertibble. These will be defined by `REDCapTidieR`.
2. Apply labels to the variables in `supertibble$redcap_metadata` and `supertibble$redcap_events`. These will be defined by `REDCapTidieR`.
3. Apply labels to the variables in `supertibble$redcap_data`. These would be derived from the contents of `supertibble$redcap_metadata`

Additionally we should add functionality for editing the labels in `redcap_metadata` before applying them to `redcap_data`. Two potential options:
1. Provide additional parameters to `make_labelled()` that control custom formatting, ex. `remove_terminal_colons`
2. Add a parameter that let's the user pass a formatting function to preprocess labels and give a sensible default, ex:
```r
formatter <- function(x) stringr::str_remove(x, ":$")

suppertibble <- make_labelled(suppertibble, label_format = formatter)
```

Finally, rather than importing `labelled` we should check that it's installed in `make_labelled()` and issue an error message if it isn't that asks the user to install it.

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by skadauke** [comment]
Great write-up of the issue! Love the idea of a formatter function but am wondering what others there might be. I'm hard pressed to think of anything other than 1) removing terminal colons and 2) limiting the length of the label. If we allow custom formatter functions then we should also give an example in the `make_labelled()` roxygen docs to explain how to create custom formatter functions.

**Comment by ezraporter** [comment]
What do we think about testing this `make_labelled()` function? I'm torn between:

**Option 1:**
Test with minimal versions of `read_redcap_tidy()` output created within the test file. So we'd have things like:
```r
fake_supertbl <- tribble(
    ~ redcap_form_name, ~ redcap_data, ~redcap_metadata,
    ...
)

out <- make_labelled(fake_supertbl)

expectations ...
```

**Option 2:**
Test with actual output of `read_redcap_tidy()` generated by `httptest` mocks. So we'd have:

```r
httptest::with_mock_api({
    out <- read_redcap_tidy(uri, token) %>%
        make_labelled()
})

expectations ...
```

Advantages of option 1: Less managing of mocks. `read_redcap_tidy` tests are independent of `make_labelled` tests so test failures will be easier to debug 

Advantages of option 2: Tests are likely more conservative. If future changes to `read_redcap_tidy` have downstream impacts on `make_labelled` we're more likely to detect it

Of course a combination of the two is also possible

**Comment by skadauke** [comment]
I think option 1 is better, not only because there are fewer mocks, but also because the test is more readable and it doesn't depend on read_redcap_tidy, so it's an actual unit test.

________________________________
From: ezraporter ***@***.***>
Sent: Tuesday, November 1, 2022 2:13 PM
To: CHOP-CGTDataOps/REDCapTidieR ***@***.***>
Cc: Stephan Kadauke ***@***.***>; Comment ***@***.***>
Subject: [External]Re: [CHOP-CGTDataOps/REDCapTidieR] [FEATURE] Create utility function to apply {labelled} labels to supertibble (Issue #64)


What do we think about testing this make_labelled() function? I'm torn between:

Option 1:
Test with minimal versions of read_redcap_tidy() output created within the test file. So we'd have things like:

fake_supertbl <- tribble(
    ~ redcap_form_name, ~ redcap_data, ~redcap_metadata,
    ...
)

out <- make_labelled(fake_supertbl)

expectations ...

Option 2:
Test with actual output of read_redcap_tidy() generated by httptest mocks. So we'd have:

httptest::with_mock_api({
    out <- read_redcap_tidy(uri, token) %>%
        make_labelled()
})

expectations ...

Advantages of option 1: Less managing of mocks. read_redcap_tidy tests are independent of make_labelled tests so test failures will be easier to debug

Advantages of option 2: Tests are likely more conservative. If future changes to read_redcap_tidy have downstream impacts on make_labelled we're more likely to detect it

Of course a combination of the two is also possible

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCHOP-CGTDataOps%2FREDCapTidieR%2Fissues%2F64%23issuecomment-1298921846&data=05%7C01%7Ckadaukes%40chop.edu%7C73c1add2542f4593b24f08dabc34cdff%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638029232237365941%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aZaRgZCsFh6NnIPu2%2Ffr2byPMYKazHA0%2FYshXwCsquI%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTGHWTH56AE66W5BQAJTKLWGFMVDANCNFSM6AAAAAARRGWPVU&data=05%7C01%7Ckadaukes%40chop.edu%7C73c1add2542f4593b24f08dabc34cdff%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638029232237365941%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TVNfCJVs8JSp2o9lnztrOArAR8lcPpddz1D2PTpR00g%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.
