### ISSUE TITLE
read_redcap_tidy should support using labels instead of raw values

### ISSUE THREAD

**Issue by skadauke** [CHOP-CGTDataOps/REDCapTidieR#8]
# Feature Request Description

Currently, the tibbles that `read_redcap_tidy` generates contain the raw values (usually but not always serial integer numbers) for  the following field types:

- dropdown-single
- radio-single
- checkbox-multiple
- yesno
- truefalse

There should be a switch to `read_redcap_tidy` (set to `TRUE` by default) to make the values contain the labels instead of raw values. 

# Proposed Solution

For the following field types, the labels are trivial and can be easily implemented programmatically:

- yesno: 0 -> `no` / 1 -> `yes` (factor)
- truefalse: 0 -> `FALSE` / 1 -> `TRUE` (logical)
- checkbox-multiple: 0 -> `FALSE` / 1 -> `TRUE` (logical)

For the following types, the mapping of raw to label can be determined using the `parse_labels` function.  

- dropdown-single
- radio-single

An important implementation detail here is that the order of the choices may have meaning. For this reason, these categorial field types should be coded as `factor` in the resulting tibble, with the levels corresponding to the order of choices.

### Checklist

- [X] The issue is atomic
- [X] The issue description is documented
- [X] The issue title describes the problem succinctly
- [X] Developers are assigned to the issue
- [X] Labels are assigned to the issue

**Comment by rsh52** [comment]
I agree we should make this an option, however it might be duplicative to tie metadata together with the `oneshot` outputs. I think we should try to use the `raw_or_label` argument in `redcap_read_oneshot` and ensure the trickle down code can support it since this already has the label data linked and formatted.

**Comment by skadauke** [comment]
@rsh52 we should discuss with Will tomorrow if the default behavior should be to report raw values or labels. If we decide to switch to labels we should make this issue super high priority because it's a massive breaking change so better roll it out before anyone is writing any code that depends on the old behavior.

**Comment by rsh52** [comment]
**To Note**:
Per conversation with Will: using labels will require factor, level, and order specifications.

**Comment by skadauke** [comment]
> **To Note**: Per conversation with Will: using labels will require factor, level, and order specifications.

Updated feature request.

**Comment by rsh52** [comment]
This has less to do with this feature and more just something I stumbled on while working on it:

An interesting thing worth noting for sanity is that REDCap automatically enforces lowercase variable names, at least on the generated checkbox outputs, despite introducing capital letters in the test database like I did:

![image](https://user-images.githubusercontent.com/38384694/184964236-f27e7482-c9fd-429e-a863-791fb754357c.png)

![image](https://user-images.githubusercontent.com/38384694/184964149-0b74f086-8258-43c0-b58b-b6e24b56900d.png)

This doesn't impact our current code because when we create `my_fields` in the extraction functions of `clean_*`, we use `starts_with` which has a default of `ignore.case = TRUE`:

```r
  # Below necessary to remove descriptive text fields
  # and to add column to indicate that form is completed
  my_fields <- db_data %>%
    select(starts_with(my_fields), paste0(my_form, "_complete")) %>%
    names()
```

**Comment by skadauke** [comment]
Interesting!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
